<?php

namespace AppBundle\Repository;

/**
 * actividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class actividadRepository extends \Doctrine\ORM\EntityRepository
{
}
