<?php
    if($_GET['kiTitulo']==1){
        print'
        [
            {
                "ksNombre":"yoga",
                "aaProfesores":["lolo","lulu"]
            }
        ]
        ';
    }
    if($_GET['kiTitulo']==2){
        print'
        [
            {
                "ksNombre":"footing",
                "aaProfesores":["lala","lele"]
            }
        ]
        ';
    }
    if($_GET['kiTitulo']==3){
        print'
        [
            {
                "ksNombre":"bodybump",
                "aaProfesores":["lili"]
            }
        ]
        ';
    }

?>